DROP TABLE IF EXISTS t_units, t_ingredients, t_users, t_roles, t_user_roles, t_tags, t_receipts, t_receipts_ing,
t_receipts_tags, t_likes CASCADE;

CREATE TABLE t_units (id integer GENERATED BY DEFAULT AS IDENTITY,
                      name text NOT NULL,
                      PRIMARY KEY(id));
CREATE TABLE t_ingredients (id integer GENERATED BY DEFAULT AS IDENTITY,
                            name text NOT NULL,
                            def_unit_id integer,
                            PRIMARY KEY (id),
                            FOREIGN KEY (def_unit_id) REFERENCES t_units ON DELETE SET NULL);

CREATE TABLE t_users (id integer GENERATED BY DEFAULT AS IDENTITY,
                      login text NOT NULL,
                      password text NOT NULL,
                      PRIMARY KEY(id));

CREATE TABLE t_roles (id integer GENERATED BY DEFAULT AS IDENTITY,
                      name text NOT NULL,
                      PRIMARY KEY (id));

CREATE table t_user_roles (user_id integer NOT NULL,
                           role_id integer NOT NULL,
                           FOREIGN KEY (user_id) REFERENCES t_users,
                           FOREIGN KEY (role_id) REFERENCES t_roles);

CREATE table t_tags (id integer GENERATED BY DEFAULT AS IDENTITY,
                   name text NOT NULL,
                   PRIMARY KEY (id));
CREATE TABLE t_receipts (id integer GENERATED BY DEFAULT AS IDENTITY,
                         title text NOT NULL,
                         content text NOT NULL,
                         picture bytea,
                         servings_count integer,
                         advice text,
                         is_deleted boolean NOT NULL DEFAULT false,
                         create_user_id integer NOT NULL,
                         create_data timestamp NOT NULL DEFAULT current_timestamp,
                         PRIMARY KEY (id),
                         FOREIGN KEY (create_user_id) REFERENCES t_users);
CREATE TABLE t_receipts_ing (receipt_id integer NOT NULL,
                             ing_id integer NOT NULL,
                             ing_count numeric,
                             ing_unit_id integer,
                             FOREIGN KEY (receipt_id) REFERENCES t_receipts,
                             FOREIGN KEY (ing_id) REFERENCES t_ingredients,
                             FOREIGN KEY (ing_unit_id) REFERENCES t_units);

CREATE TABLE t_receipts_tags (receipt_id integer NOT NULL,
                              tag_id integer NOT NULL,
                              FOREIGN KEY (receipt_id) REFERENCES t_receipts,
                              FOREIGN KEY (tag_id) REFERENCES t_tags);

CREATE TABLE t_likes (receipt_id integer NOT NULL,
                      user_id integer NOT NULL,
                      FOREIGN KEY (receipt_id) REFERENCES t_receipts,
                      FOREIGN KEY (user_id) REFERENCES t_users);



